# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pwnny's Blog
email: 13971099040@163.com
description: > # this means to ignore newlines until "baseurl:"
  All about HTML, CSS, JavaScript<br/>
  Copyright © Pwnny's Blog<br/>
baseurl: "" # the subpath of your site, e.g. /blog
url: "pwnny.cn" # the base hostname & protocol for your site
github_username:  zyc8904

# Build settings
markdown: Kramdown
